Hotfix: put-file cannot fail on first upload
Apparently, latest GitLab will raise

gitlab.exceptions.GitlabGetError: 404: 404 invalid revision or path Not Found

when the remote file (or the directory) does not exist before calling
put-file. The added early return should fix that.